### ISSUE TITLE
Preliminary results for old Firebird

### ISSUE THREAD

**Issue by SenerDemiral** [miyconst/StarcounterReferenceBenchamrk#1]
This test results based on Database stored-procedure. (No network overhead like in-memory)
Primary and Foreign keys used.
I can't measured for 5 runs.
1000 Runs read 101,000 records (1K for Parent 100K for Child)
125 msec!

**Comment by SenerDemiral** [comment]
C# Windows Form Application with using the DataSet
5 Runs : 00:00:01.6207
```
Stopwatch watch = new Stopwatch();

watch.Start();

for(int i = 0; i < 5; i++) {
	dataSet.PRNT.Clear();
	dataSet.CHLD.Clear();

	prntTableAdapter.Fill( dataSet.PRNT );
	foreach(var c in this.dataSet.PRNT) {
		chldTableAdapter.FillByPID( dataSet.CHLD, c.ID );
	}
}
watch.Stop();
MessageBox.Show(string.Format("Compare took: {0}", watch.Elapsed));
```

**Comment by miyconst** [comment]
>1000 Runs read 101,000 records (1K for Parent 100K for Child)

Can you explain this a bit more? What you numbers mean? Also, keep in mind that your numbers can't be compared to my numbers, since we have different machines.

>I can't measured for 5 runs.

Why?

>C# Windows Form Application with using the DataSet
5 Runs : 00:00:01.6207

So, if comparing with my numbers (which is not correct), it is:

- 3 times slower compare to Starcounter without index. 1.6 seconds against 0.5 seconds.
- 40 times slower compare to Starcounter with index. 1.6 seconds against 0.04 seconds.

**Comment by miyconst** [comment]
Could you please:

- Run my benchmark on your machine and share the results.
- Run exactly the same benchmark using Firebird and also share the results.
- Combine the results in one table, similar to the one in the readme file.

**Comment by SenerDemiral** [comment]
Results on my PC

Comparison	| Runs |	Elapsed (seconds) | Firebird* | Firebird**
------------|----|-----------|-------------|----
Object comparison without index |	5 |	00.3103007 | N/A | N/A
Object no comparison without index|	5 |	02.6019145 | x | x
Object comparison with index |	5 |	00.0120182 | N/A | N/A
Object no comparison with index |	5 |	00.0178890 | 01.6207 | 0.001265

Nots
Starcounter ObjectNo = Firebird relation ID
Firebird*  
Get data from DB to Client Windows Application
1. Connect DB
2. Fill ADO.DataSet by Firebird adapter

Firebird**
Raw performance, In database stored-procedure (simulated C# code)
1. Run stored-procedure from Firebird DB tool like IBExpert.

**Comment by miyconst** [comment]
Thanks! This is something we can evaluate.

So, comparing to Firebird with identical condition, Starcounter seems to be 10 times slower. Let's make sure that this is actually an identical comparison.

When you select a record in Starcounter you get instant access to the object, including all of it's properties. Does it also apply to Firebird? Could you please share your Firebird code, so I can google a bit and learn it.

I want to check, whether Firebird version retrieves entire row with all the values from the database, or just it's primary key value.

**Comment by SenerDemiral** [comment]
```
select List(cName) from PRNT_CHLD_TEST (5000)
```
returns all cName in one Text Blob. (~5MB)


```
create or alter procedure PRNT_CHLD_TEST (
    ITRCNT D_I)
returns (
    PID D_I,
    PNAME D_100,
    CID D_I,
    CNAME D_100)
AS
declare variable i  D_I;
begin
  i = 0;
  while (i < itrCnt) do
  begin
    for select ID, Name
          from Prnt
          into :pID, :pName
    do
    begin
      for select ID, Name
            from Chld
           where pID = :pID
            into :cID, :cName
      do
      begin
        SUSPEND;
      end

      i = i + 1;
    end
  end
end
```
Query
------------------------------------------------
select List(cName) from Prnt_chld_test(5000)

Plan
------------------------------------------------
PLAN (CHLD INDEX (FK_CHLD_PRNT))(PRNT NATURAL)

Query Time
------------------------------------------------
Prepare       : 0.00 ms
Execute       : 1,250.00 ms
Avg fetch time: 1,250.00 ms

Memory
------------------------------------------------
Current: 35,302,328
Max    : 35,397,664
Buffers: 2,048

Operations
------------------------------------------------
Read   : 1
Writes : 0
Fetches: 1,026,100
Marks  : 850

![image](https://cloud.githubusercontent.com/assets/3463333/22082870/2a7dc04a-ddd2-11e6-8ba7-cf6e859232f4.png)

**Comment by miyconst** [comment]
Thanks for the detailed information!

@k-rus, could you please take a look?

**Comment by k-rus** [comment]
I guess I will start by trying this repo app on latest Starcounter's installer.

**Comment by miyconst** [comment]
@SenerDemiral it looks like Firebird has some kind of optimization or cashing, which detects execution of the same statements, and uses some smart caching.

I have downloaded and installed Firebird 3.0.1, created identical database, and a stored procedure:

```sql
SET TERM !! ;

CREATE PROCEDURE Run AS

DECLARE total int;
DECLARE i int;
DECLARE id int;

DECLARE childId int;
DECLARE childParentId int;
DECLARE childName varchar(250);

BEGIN
	total = 5;
	i = 0;
	
	DELETE FROM ChildPerParent;
	
	WHILE (i < total) DO
	BEGIN
		FOR SELECT Id FROM Parent
			INTO :id
		DO
		BEGIN
			INSERT INTO ChildPerParent (Id, ParentId, Name)
			SELECT Child.Id, Child.ParentId, Child.Name
			FROM Child
			WHERE Child.ParentId = :id;
		END
		
		i = i + 1;
	END

END !!

SET TERM ; !!
```

The `ChildPerParent` is a temp table declared as following:

```sql
CREATE GLOBAL TEMPORARY TABLE ChildPerParent (Id int, ParentId int, Name varchar(250));
```

Since Firebird does not support `table` variable and does not support creation of tables inside a stored procedure, I think this is the only way to mimic `List<T>` from c#. Please correct me if I am wrong.

In this case the benchmark time is far slower compare to Starcounter or your procedure.

This thread reminds me an old joke. Two developers talk to each other:

- You know what? I have made a zipper which zips everything to 1 byte.
- Really? That can't be possible.
- Well, I don't yet have the un-zipper for it.

Even if Firebird would be faster than Starcounter, this comparison is a bit of pointless. Starcounter if an app development platform, and every data selected is instantly available for your application. While data selected inside a stored procedure of Firebird has to be transferred to an app to be useful. No one is going to develop a business app using Firebird stored procedures only. 

If you still insist on further investigation, please share your entire database and reopen the issue.

**Comment by SenerDemiral** [comment]
Yes you are correct.
Real scenario is get records from DB to Client app which is indicated as Firebird* column.
But you can not deny internal (stored-procedure) performance of Firebird, cached, optimized or whatever is.
Think of that, If stored-procedure makes million of records process and produce little amount of records.

All oldSQL developers use some DB management tools manipulate the structure of DB.
I used IBexpert tool to make Table/Data creation/modification etc.
I insistly think **Starcounter** also should have such kind of tools.
It could even do a simple Insert/Update/Delete operation, Our life would be easier!

Anyway you are trying to do fantastic thing and we are using it with great enthusiasm.
Thanks all of you.

**Comment by miyconst** [comment]
>All oldSQL developers use some DB management tools manipulate the structure of DB.
I used IBexpert tool to make Table/Data creation/modification etc.
I insistly think Starcounter also should have such kind of tools.

Absolutely! We already have this planned in our backlogs.

**Comment by k-rus** [comment]
> Thanks for the detailed information!
> 
> @k-rus, could you please take a look?

I get similar numbers when I run this repo test. Do I interpret it correctly that each iteration read 100 parents and 100 child for each parent, i.e., 10000 reads, if insert was called only once? So 50000 reads in a single transaction takes 12 ms, right?
Then I think the numbers are reasonable. I expect that 1 transaction with a select query, which reads a single record into C# application code, takes approximately 2-3 mcs on a Windows laptop.

**Comment by SenerDemiral** [comment]
Yes,
Insert was called only once.
Each iteration reads 100 parent and for each parent reads 100 child.
Actually in one iteration 100 + 100*100 = 11K records read.

Sorry! I'm absolutely **WRONG,** because iteration count position is wrong in stored-procedure.
I corrected stored-procedure and above comparison chart.
I relieved. I already could not believe the numbers before. I am more happy now.
Starcounter is 
  90 times faster than Firebird in Windows App.
  even 7 times faster than Firebird stored-procedure.
```
create or alter procedure PRNT_CHLD_TEST (
    ITRCNT D_I)
returns (
    PID D_I,
    PNAME D_100,
    CID D_I,
    CNAME D_100)
AS
declare variable i  D_I;
begin
  i = 0;
  while (i < itrCnt) do
  begin
    for select ID, Name
          from Prnt
          into :pID, :pName
    do
    begin
      for select ID, Name
            from Chld
           where pID = :pID
            into :cID, :cName
      do
      begin
        SUSPEND;
      end
      --i = i + 1;     This is the wrong place of iterarion count
    end
    i = i + 1;   --Correct place
  end
end
```
New results for 5 iteration
![image](https://cloud.githubusercontent.com/assets/3463333/22143453/c0788464-df02-11e6-99c9-218ec2056321.png)

Query
------------------------------------------------
select List(cName) from Prnt_chld_test(5)

Plan
------------------------------------------------
PLAN (CHLD INDEX (FK_CHLD_PRNT))(PRNT NATURAL)

Query Time
------------------------------------------------
Prepare       : 0.00 ms
Execute       : 125.00 ms
Avg fetch time: 125.00 ms

Memory
------------------------------------------------
Current: 35,201,776
Max    : 35,287,928
Buffers: 2,048

Operations
------------------------------------------------
Read   : 0
Writes : 0
Fetches: 145,482
Marks  : 86

Again thank you for your tolerance.

**Comment by k-rus** [comment]
@SenerDemiral Thank you for the finding!
Now it corresponds to our previous internal benchmarks, that Starcounter beats stored procedures in commercial DBMSs by 5-10 times.

**Comment by miyconst** [comment]
@k-rus thank you very much for taking a part in this investigation!

**Comment by SenerDemiral** [comment]
That's it!

**Comment by SenerDemiral** [comment]
@miyconst do you want me to close this issue?

**Comment by miyconst** [comment]
>@miyconst do you want me to close this issue?

Is not it already closed?

**Comment by SenerDemiral** [comment]
You are again right!
